name: Auto update

on:
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt-get install openssh-client python3-setuptools

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          repository: Kshao123/genpac
          path: genpac

      - uses: actions/checkout@v4
        with:
          repository: gfwlist/gfwlist
          path: gfwlist

      - run: |
          cd genpac
          sudo python3 setup.py install
      - name: Update
        run: |
          set -x
          ls -la
          cat ../user-rules.txt
#         --pac-proxy pac 的代理地址；--gfwlist-url 为 - 时不从线上获取规则；
#          genpac --pac-proxy "SOCKS5 127.0.0.1:7890; SOCKS 127.0.0.1:7890; DIRECT;" --gfwlist-url - --gfwlist-local demo/gfwlist.txt -o demo/gfwlist.pac --user-rule-from demo/user-rules.txt
#         删除1-7行 -i 在当前文件执行
#          sed '1,7d' -i gfwlist.pac

#          git add gfwlist.pac
#          git commit -m "[$(LANG=C date)] auto update" || exit 0

#          [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit 0

#          git push origin master
