name: Auto update

on:
  push:
    branches:
      - master
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt-get install openssh-client python3-setuptools

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4
        with:
          repository: Kshao123/genpac
          path: genpac

      - uses: actions/checkout@v4
        with:
          repository: gfwlist/gfwlist
          path: gfwlist

      - run: |
          cd genpac
          sudo python3 setup.py install
      - name: Update GfwList
        id: updateList
#        set -x 开启详细输出日志模式
#        --pac-proxy pac 的代理地址；--gfwlist-url 为 - 时不从线上获取规则；
        run: |
          set -x
          genpac --pac-proxy "SOCKS5 127.0.0.1:7890; SOCKS 127.0.0.1:7890; DIRECT;" --gfwlist-url - --gfwlist-local gfwlist/gfwlist.txt -o gfwlist.pac --user-rule-from user-rules.txt
#         删除1-7行 -i 在当前文件执行
#         sed '1,7d' -i gfwlist.pac

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[$(LANG=C date)] auto update"

      - name: down
        run: echo "update down"
